services:
  - name: golang-backend
    type: web
    env: go
    region: Frankfurt
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
          property: connectionString
      - key: JWT_SECRET
        sync: false
